-- Run in Supabase SQL editor
ALTER TABLE users ADD COLUMN IF NOT EXISTS bag_issued BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bag_issued_by UUID REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bag_issued_at TIMESTAMPTZ;
